name: Deploy

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install WebAssembly target
      run: rustup target add wasm32-unknown-unknown
    
    - name: Install trunk
      run: cargo install trunk
      
    - name: Build
      run: trunk build --release
    
    - name: Copy index.html for 404-page
      run: cp dist/index.html dist/404.html
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
        clean: true
